name: Idea / Ideia
description: Propose an idea or improvement
title: "[Idea]: "
labels: ["idea"]
body:
  - type: textarea
    id: what
    attributes:
      label: What is the idea?
      description: PT/EN welcome.
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why does it matter?
    validations:
      required: false
